<?php
    $customStyles = array(
    	'backgroundColor'        => '#3A3A3A',
    	'mainLinkColor'          => '#000276',
    	'mainLinkHoverColor'     => '#0069BA',
    	'mainHeaderColor'        => '#10AEE5',
    	'mainHeaderLinkColor'    => '#A6A6CD',
    	'secondHeaderLinkColor'  => '#0095CC',
    	'contentTextColor'       => '#3A3A3A',
    	'mainAccentColor'        => '#F64D19',
    	'fimageTitleColor'       => '#F3F6F9',
    	'borderColor'            => '#001369',
    	'dropdownMenuColor'      => '#B3B3DA',
    	'dropdownMenuBg'         => 'inherit',
    	'dropdownSubMenuBg'      => '#E5E5E5',
    	'dropdownMenuHoverColor' => '#A6A6CD',
    	'dropdownMenuColor'      => '#A6A6CD',
    	'dropdownMenuHoverBg'    => 'rgba(85,85,85,0.97)',
    	'subMenuBorderColor'     => 'rgba(85,85,85,0.97)',
    	'dropdownMenuShadow'     => '0px 1px 1px 1px #555',
    	'subMenuColor'           => $dropdownMenuColor,
    	'subMenuHoverColor'      => '#4DE2FF',
    	'headerColor'            => '#007539',
    	'sidebarLinkColor'       => $mainLinkHoverColor,
    	'sidebarLinkHoverColor'  => $borderColor,
    	'footerLinkColor'        => '#008BC3',
    	'footerLinkHoverColor'   => '#1ABEF6',
    	'commentsBgHoverColor'   => 'rgba(255,255,255,0.7)',
    );
    require("template.min.php");  
?>