<?php
    return array(
        'stylesheetTemplate'     => 'template',
    	'backgroundColor'        => '#FFF',
    	'mainLinkColor'          => '#008BC3',
    	'mainLinkHoverColor'     => '#1ABEF6',
    	'mainHeaderColor'        => '#10AEE5',
    	'mainHeaderLinkColor'    => '#000276',
    	'secondHeaderLinkColor'  => '#0095CC',
    	'contentTextColor'       => '#3A3A3A',
    	'mainAccentColor'        => '#F64D19',
    	'fimageTitleColor'       => '#F3F6F9',
    	'borderColor'            => '#000276',
    	'dropdownMenuColor'      => '#B3B3DA',
    	'dropdownMenuBg'         => '#FFF',
    	'dropdownSubMenuBg'      => '#FFF',
    	'dropdownMenuHoverColor' => '#000276',
    	'dropdownMenuColor'      => '#000276',
    	'dropdownMenuHoverBg'    => '#EFEFEF',
    	'subMenuBorderColor'     => 'rgb(85,85,85,0.97)',
    	'dropdownMenuShadow'     => '6px 0px 10px 2px #666',
    	'subMenuColor'           => '#000276',
    	'subMenuHoverColor'      => '#4DE2FF',
    	'headerColor'            => '#00398F',
    	'sidebarLinkColor'       => '#0069BA',
    	'sidebarLinkHoverColor'  => '#001369',
    	'footerLinkColor'        => '#000276',
    	'footerLinkHoverColor'   => '#0069BA',
    	'commentsBgHoverColor'   => 'rgba(255,255,255,0.7)',
    );
    require("template.min.php"); 
?>
